batch_size: 32
lr: 1.0e-5
batch_norm: False
basic_model: vgg16
regweight: 0.5
gpu: 1
save_dir: ckpt/attr
#save_dir: ckpt/box
path_base: /home/arcthing/qiaohan/data/cloth_data/DeepFashion/CSCRB/Img/
datalist_file: datalist/CSCRB_label_train.txt
test_datalist_file: datalist/CSCRB_label_test.txt
#datalist_file: datalist/attrsam.txt
save_period: 5000
num_epochs: 5
#image format
channels: 3
bgr: False
crop_shape:
  w: 225
  h: 300
scale_shape:
  w: 224
  h: 224
