batch_size: 33
lr: 8.0e-3
batch_norm: False
basic_model: vgg16
regweight: 0.5
margin: 0.2
gpu: 6
#save_dir: ckpt/attr
save_dir: ckpt/ltr
path_base: /home/arcthing/qiaohan/data/cloth_data/DeepFashion/CSCRB/Img/
datalist_file: datalist/CSCRB_train.txt
test_datalist_file: datalist/CSCRB_test.txt
#datalist_file: datalist/attrsam.txt
save_period: 5000
num_epochs: 15
#image format
roipool: True
channels: 3
bgr: False
crop_shape:
  w: 225
  h: 300
scale_shape:
  w: 224
  h: 224
